// <auto-generated />
namespace LeaveManagementSystem.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class datetimenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161729226_datetime-nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
